const PEDIDO_PENDENTE = 'pendente';
const PEDIDO_ACEITO = 'aceito';
const PEDIDO_RECUSADO = 'recusado';
const PEDIDO_CANCELADO = 'cancelado';
const PEDIDO_EM_REAVALIACAO = 'em reavaliação';

export {
  PEDIDO_PENDENTE, PEDIDO_ACEITO, PEDIDO_RECUSADO, PEDIDO_CANCELADO, PEDIDO_EM_REAVALIACAO,
};
